#!/bin/bash
set -x

if [ -f "/Library/PrivilegedHelperTools/com.renewedvision.InstallHelper" ]; then
    if [ -f "/Library/LaunchDaemons/com.renewedvision.InstallHelper.plist" ]; then
        /bin/launchctl unload /Library/LaunchDaemons/com.renewedvision.InstallHelper.plist
        rm /Library/LaunchDaemons/com.renewedvision.InstallHelper.plist
    fi
    rm -f /Library/PrivilegedHelperTools/com.renewedvision.InstallHelper
fi

# Load the LaunchDaemons
/bin/launchctl load /Library/LaunchDaemons/com.renewedvision.Helper.plist
